// require("./src/warmup/ifElse");
// require("./src/warmup/loop01");
// require("./src/warmup/loop02");
// require("./src/warmup/secondLargest");
// require("./src/warmup/pattern");
// require("./src/warmup/countDigit");
// require("./src/warmup/palindrome");
// require("./src/warmup/reverseInteger");
// require("./src/Array-Level-0/RemoveDuplicates");
// require("./src/Array-Level-0/Remove_Element");
// require("./src/Array-Level-0/Reverse_String");
// require("./src/Array-Level-0/Sell_Buy_Stocks");
// require("./src/Array-Level-0/Merge_Sorted_Array");
// require("./src/Array-Level-0/Move_Zero");
// require("./src/Array-Level-0/Max_Consecutive_Ones");
// require("./src/Array-Level-0/Single_Number");
// require("./src/Recursion101.js/Print_n_to_1");
// require("./src/Recursion101.js/Print_1_to_n");
// require("./src/Recursion101.js/Sum_first_n");
// require("./src/Recursion101.js/Sum_All_Element_arr");
// require("./src/Recursion101.js/Factorial");
// require("./src/Recursion101.js/Power_Of_Two");
// require("./src/Search/linear_search");
// require("./src/Search/binary_search")
// require("./src/Search/bubble_sort")
// require("./src/Search/selection_sort")
// require("./src/Sort/insertion_sort")
require("./src/Sort/merge_sort")
