// require("./src/warmup/ifElse");
// require("./src/warmup/loop01");
// require("./src/warmup/loop02");
// require("./src/warmup/secondLargest");
// require("./src/warmup/pattern");
// require("./src/warmup/countDigit");
// require("./src/warmup/palindrome");
// require("./src/warmup/reverseInteger");
// require("./src/Array-Level-0/RemoveDuplicates");
// require("./src/Array-Level-0/Remove_Element");
// require("./src/Array-Level-0/Reverse_String");
// require("./src/Array-Level-0/Sell_Buy_Stocks");
// require("./src/Array-Level-0/Merge_Sorted_Array");
// require("./src/Array-Level-0/Move_Zero");
// require("./src/Array-Level-0/Max_Consecutive_Ones");
require("./src/Array-Level-0/Single_Number");
